[package]
name = "frender"
version = "0.1.0" # replace version
authors = ["EqualMa <equalma@outlook.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.63"
forgotten = "1"
js-sys = "0.3"
once_cell = "1.8"

[dependencies.react-rs]
path = "../crates/react"
version = "0.1.0" # replace version

[dependencies.web-sys]
version = "0.3"
features = [
    "console",
    "Window",
    "Document",
    "Element",
]

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
