[package]
name = "frender"
version = "0.1.0"
authors = ["EqualMa <equalma@outlook.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.63"
react-sys = "1.0.0-alpha.4"

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
