[package]
name = "frender"
version = "0.1.0"
authors = ["EqualMa <equalma@outlook.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.63"
react-sys = "1.0.0-alpha.11"
forgotten = "1"
js-sys = "0.3"
once_cell = "1.8"

[dependencies.web-sys]
version = "0.3"
features = [
    "console",
    "Window",
    "Document",
    "Element",
]

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
