[workspace]

members = [
    #
    "frender",
    "crates/*",
    "examples/*",
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[replace]
"callable:0.3.0" = { path = "../callable" }
