[package]
name = "frender-hook-element"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frender-core = { path = "../frender-core", version = "0.1.0" }
frender-dom = { path = "../frender-dom", version = "0.1.0", optional = true }
frender-ssr = { path = "../frender-ssr", version = "0.1.0", optional = true }
pin-project-lite = "0.2.9"
bg = "0.2.0"
frender-macros = { version = "1.0.0-alpha.8", path = "../frender-macros" }
lazy-pinned = "0.1.0"

[dependencies.hooks]
version = "1.0.1-alpha.20"
default-features = false
features = ["derive"]

[features]
dom = ["frender-dom"]
spawn = ["frender-dom?/spawn"]
ssr = ["dep:frender-ssr"]
