def_props_type!(
    #[derive(Debug, Clone, Copy, Default)]
    Element(
        children,
        css: bounds![Css::Bounds],
        class: bounds![DomTokens::Bounds],
        id: bounds![crate::imports::impl_bounds::MaybeValue::Bounds<str>],
        part: bounds![crate::imports::impl_bounds::MaybeValue::Bounds<str>],
        on_cancel:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_cancel)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_error:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_error)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_scroll:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_scroll)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_security_policy_violation:
            bounds![
                #[event(crate
    ::imports::frender_html::html::event_type_helpers::on_security_policy_violation)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_select:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_select)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_wheel:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_wheel)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_copy:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_copy)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_cut:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_cut)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_paste:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_paste)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_composition_end:
            bounds![
                #[event(
                    crate::imports::frender_html::html::event_type_helpers::on_composition_end
                )]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_composition_start:
            bounds![
                #[event(
                    crate::imports::frender_html::html::event_type_helpers::on_composition_start
                )]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_composition_update:
            bounds![
                #[event(
                    crate::imports::frender_html::html::event_type_helpers::on_composition_update
                )]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_blur:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_blur)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_focus:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_focus)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_focus_in:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_focus_in)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_focus_out:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_focus_out)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_fullscreen_change:
            bounds![
                #[event(
                    crate::imports::frender_html::html::event_type_helpers::on_fullscreen_change
                )]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_fullscreen_error:
            bounds![
                #[event(
                    crate::imports::frender_html::html::event_type_helpers::on_fullscreen_error
                )]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_key_down:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_key_down)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_key_up:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_key_up)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_aux_click:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_aux_click)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_click:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_click)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_context_menu:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_context_menu)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_double_click:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_double_click)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_mouse_down:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_mouse_down)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_mouse_enter:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_mouse_enter)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_mouse_leave:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_mouse_leave)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_mouse_move:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_mouse_move)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_mouse_out:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_mouse_out)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_mouse_over:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_mouse_over)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_mouse_up:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_mouse_up)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_touch_cancel:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_touch_cancel)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_touch_end:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_touch_end)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_touch_move:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_touch_move)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
        on_touch_start:
            bounds![
                #[event(crate::imports::frender_html::html::event_type_helpers::on_touch_start)]
                crate::imports::impl_bounds::MaybeHandleEvent::Bounds
            ],
    )
);
mod imports {
    #[allow(unused_imports)]
    use super::super::*;
    pub(super) use crate::imports::frender_html_simple::def_props_type;
}
use imports::def_props_type;
