[package]
name = "tic-tac-toe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frender = { path = "../../frender", features = ["dom", "spawn", "bg"] }
hooks = "2.0.2-alpha"
gloo = "0.8.0"
