[package]
name = "counter-no-proc-macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frender = { path = "../../frender", features = ["web", "spawn"] }
gloo = "0.8.0"
hooks = "3.0.0-alpha"
