name: Release
on:
  push:
    branches:
      - main
      - alpha
      - beta

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Setup wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      # https://github.com/actions/cache/blob/master/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(./.yarn/cache)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --immutable
      - name: Ensure linted
        run: yarn run ensure-linted
      - name: Rust Build & Test
        run: cargo build --verbose && cargo test --verbose
      - name: Test
        run: |
          set -e
          cargo check --verbose
          cargo test --verbose
          wasm-pack test --node frender
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          if [ -z "$GITHUB_TOKEN" ]; then
            echo 'Unexpected empty GITHUB_TOKEN' >&2
            exit 1
          fi
          if [ -z "$CARGO_REGISTRY_TOKEN" ]; then
            echo 'Please set secrets.CARGO_REGISTRY_TOKEN' >&2
            exit 1
          fi
          yarn run semantic-release
